### ISSUE TITLE
Ability to add a path in the filesystem dialog

### ISSUE THREAD

**Issue by D3473R** [OpenMediaVault-Plugin-Developers/openmediavault-unionfilesystems#34]
Hi,

i want to add a path option to the filesystem dialog.
I thought about something like in the following screenshot.
![Screenshot from 2020-01-04 14-41-25](https://user-images.githubusercontent.com/10356892/71766458-6a691b00-2f00-11ea-88a5-3cf2e0d592b7.png)
Reason is I don't want to merge the whole disks, only a directory on them.
I this example the folder `merge1` on `dev/sdb1` with the folder `merge2` on `dev/sdc1`.

In fstab i want to get from:
`/srv/dev-disk-by-label-merge1:/srv/dev-disk-by-label-merge2 /srv/some-uuid fuse.mergerfs some-options`
to:
`/srv/dev-disk-by-label-merge1/merge1:/srv/dev-disk-by-label-merge2/merge2 /srv/some-uuid fuse.mergerfs some-options`

Now I have two questions.
1. How do i get the transifex variable for `path` registered?
2. How can i add an input field for `path` in the grid?

Regards,
D3473R

**Comment by ryecoaaron** [comment]
I appreciate the help.  I have actually been slowly working on this but I don't want to change the primary pooling tab to use paths because I think it makes it complicated (some users don't understand Linux paths).  I also don't want to limit the number of folders to pool to the number of drives.

1 - There are two transifex commands that I have automated.  The first command generates the file that has all of the strings to translate.  The second command uploads it to transifex making it available in the plugin's project for translation.

2 - Not sure.  Never looked into it.  I don't think there are any other plugins using that where I could point you at.

**Comment by ryecoaaron** [comment]
The mergerfsfolders plugin should do what you want and is available on OMV 5.x.
